---
- name: copy firefoy profile
  unarchive:
    src: files/firefox-profile.zip
    dest: "{{home_dir}}.config/firefox/"

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: "{{home_dir}}.config/firefox/"
    state: directory
    recurse: yes
    owner: '{{ user_name }}'
    mode: '0755'
